# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tielubot_filter_noInterval

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.0"

    - name: Install virtualenv
      run: pip install virtualenv

    - name: Create virtual environment
      run: python -m venv env

    - name: Activate virtual environment and upgrade pip
      run: |
        .\env\Scripts\activate
        python -m pip install --upgrade pip

    - name: Install playsound
      run: pip install playsound

    - name: Install other dependencies
      run: pip install pyautogui pyperclip requests datetime pyinstaller

    
    - name: pyinstaller
      run: |
        pyinstaller -F -i 预警.ico main.py
        echo 'exe打包完成'
        ren dist/main.exe 舆情预警_关键词过滤_无间隔.exe
        echo 'exe重命名完成'
        move dist/舆情预警_关键词过滤_无间隔.exe ./
        echo 'exe移动完成'
        ren main.py 舆情预警_源码.py
        echo '源码重命名完成'
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tielubot_filter_noInterval
        path: |
          舆情预警_关键词过滤_无间隔.exe
          舆情预警_源码.py
          start.wav
          warning.wav
          dingdong.mp3
          properties.txt
          keywords.txt
