# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tielubot_filter_noInterval

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pyautogui pyperclip requests datetime
        pip install pyinstaller
    
    - name: pyinstaller
      run: |
        pyinstaller -F -i 预警.ico main.py
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tielubot_filter_noInterval
        path: |
          dist
          properties.txt
          keywords.txt
